const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Car,
		C3.Behaviors.scrollto,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Behaviors.Fade,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Behaviors.Car.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.int,
		C3.Behaviors.Car.Exps.Speed,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Car.Acts.SetMaxSpeed,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Car.Acts.Stop,
		C3.Behaviors.Car.Acts.SetSpeed,
		C3.Behaviors.Car.Acts.SetAcceleration,
		C3.Plugins.System.Acts.RestartLayout
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Wall: 0},
	{Nitro: 0},
	{Nitrando: 0},
	{HP: 0},
	{Car: 0},
	{ScrollTo: 0},
	{Ship: 0},
	{SpeedText: 0},
	{Keyboard: 0},
	{NitroItem: 0},
	{HPText: 0},
	{Fade: 0},
	{ShipShadow: 0},
	{Finish: 0},
	{Instructions: 0},
	{NitroSpawn01: 0},
	{NitroSpawn02: 0},
	{NitroSpawn03: 0},
	{NitroSpawn04: 0},
	{Audio: 0},
	{Countdown: 0},
	{CountdownBG: 0},
	{NitroRandom: 0}
];

self.InstanceType = {
	Wall: class extends self.ISpriteInstance {},
	Ship: class extends self.ISpriteInstance {},
	SpeedText: class extends self.ITextInstance {},
	Nitro: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	NitroItem: class extends self.ISpriteInstance {},
	HPText: class extends self.ITextInstance {},
	ShipShadow: class extends self.ISpriteInstance {},
	Finish: class extends self.ISpriteInstance {},
	Instructions: class extends self.ITextInstance {},
	NitroSpawn01: class extends self.ISpriteInstance {},
	NitroSpawn02: class extends self.ISpriteInstance {},
	NitroSpawn03: class extends self.ISpriteInstance {},
	NitroSpawn04: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Countdown: class extends self.ITextInstance {},
	CountdownBG: class extends self.ISpriteInstance {}
}